<!DOCTYPE html>
<html lang="en">
<head>
	
		<title>Surfers Co.</title>
		
		<?php include("inc/inc_head.php");	?>
	<script>
		
		function InviaDati()
        {
			var config = {
					 url: 'cookie.php'
					,success: AccettaCookie                                  			
					}	 
			$.ajax(config);
        }
	
		function AccettaCookie(){
			$( "#cookies" ).hide();
		}
		
		function Chiudi(){
			$( "#banner" ).hide();
		}		
		
	</script>
</head>
<body>
	<?php 
		
		if(!isset($_COOKIE['mio_cookie'])) {

	?>
		<div id="cookies" class="container">Questo sito utilizza i cookies. Utilizzando il nostro sito web l'utente dichiara di accettare e acconsentire all’utilizzo dei cookies in conformità con i termini di uso dei cookies espressi in questo documento. 
			Acconsento e proseguo la navigazione <input type="checkbox" onchange="InviaDati(), AccettaCookie()" id="closeCookie"></input>
		</div>
		
	<?php
		} //endif
	?>
		
	<?php include("inc/inc_header.php"); ?>
	
	<div id="banner">
		
		<button type="button" id="chiudi" onclick="Chiudi()" class="btn btn-primary"> x </button>
		<h2 class="text-center">Best Offers</h2>
		<a href="offerta.php"><img class="img-responsive" src="banner.jpg" alt=""></a>
	</div>
	
	<main class="larghezza-cento">
		<div id="promotion" class="larghezza-ottanta">
			<div id="immagine-promo" class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
				<img src="images/img1.jpg" class="img-responsive center-block" alt="" id="myImg1"/>
				<img src="images/img2.jpg" class="img-responsive center-block" alt="" id="myImg2"/>
				<br/>
				<br/>
				<button type="button" id="prev" onclick="scorri()" class="btn btn-primary"> &lt; </button>
				<button type="button" id="next" onclick="scorri()" class="btn btn-primary"> &gt; </button>
				<br/>
				<br/>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-6" id="promo1">
								
				<br/>
				<br/>
				<br/>
				<h4>JR Surfboards The Donny Stoker <br/> Yellow/Green Rail Fade</h4>
				<ul>
					
					<li><a href="#">DESCRIPTION</a></li>
					<li><a href="#">FEATURES</a></li>
					<li><a href="#">DIMENSIONS</a></li>
					
				</ul>
				<p> Easy to ride, care free surfing craft tha's fun for everyone,
					paddles well, super fast down the line and grat for any level of surfing depending
					on who rides it. The Donny Stoker, a rework on design from stokesys first ever pro model.
					A super easy to surf and fun board. The Donny Stoker is a board for total
					freesurfing expression. Easy to ride, care free surfing craft tha's fun for everyone,
					paddles well, super fast down the line and grat for any level of surfing depending
					on who rides it.
				</p>
				<h3>$499.99 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<button type="button" class="btn btn-primary">BUY NOW</button>
				</h3>
				<br/>
				<br/>
				<br/>
				
				<a href="#">View all boards</a>
				<h1>BOARDS</h1>
				
			</div>
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-6" id="promo2">
			
				<br/>
				<br/>
				<br/>
				<h4>KSP Surfboards Wave <br/> White/Light Blue Rail Fade</h4>
				<ul>
					
					<li><a href="#">DESCRIPTION</a></li>
					<li><a href="#">FEATURES</a></li>
					<li><a href="#">DIMENSIONS</a></li>
					
				</ul>
				<p>
					Due to its entirely 3D construction, it presents different grip lines that give a good grip (even with no fins), 
					both in gliding and in landing, and a more aggressive pop .This table has been produced with a technology that make it really strong,
					able to withstand any landing, and any kind of abuse by the most aggressive riders.
					KSP board collections also present in each model PVC reinforced clutches for the use of boots. 
					Using them with the most aggressive maneuvers, won't be a problem no more.
					Made with Varial-X Carbon hight-level torsion system, this board will withstand stresses very strong, is able to transform the energy generated by the rider, in extreme trick.
					Trick impressive and soft landings to give the best of your freestyle at full power!
				</p>
				<h3>$559.99 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<button type="button" class="btn btn-primary">BUY NOW</button>
				</h3>
				<br/>
				<br/>
				<br/>
				
				<a href="#">View all boards</a>
				<h1>BOARDS</h1>
				
			</div>
			
			
			
			
		</div>
		
		<div class="larghezza-cento">
			<div id="about" class="col-lg-12 larghezza-cento">
						
						<br/>
						<br/>
						<br/>
				<h1>ABOUT US</h1>
						
						
				
			</div>
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="about-alto">
				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" id="bianco">
					<div class="col-xs-0 col-sm-0 col-md-3 col-lg-4"></div>
					<div id="about-testo" class="col-xs-12 col-sm-12 col-md-7 col-lg-6">
						<br/>
						<br/>
						<br/>
						<br/>
						<h5>WE ARE SURFERS CO.</h5>
						<br/>
						<p>
						Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore 
						et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam,
						nisi ut aliquid ex ea commodi consequatur. Quis aute iure reprehenderit in voluptate velit esse cillum dolore
						eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, 
						sunt in culpa qui officia deserunt mollit anim id est laborum.
						Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore 
						et dolore magna aliqua.
						</p>
					
						<br/>
						<br/>
						<a href="#">Read more</a>
						
					</div>

				
				</div>
            </div>  
				 
				
			
			<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
			</div>
			
			<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
				<div class="youtube-container" id="video">
					<div class="youtube-player" data-id="VIDEOID">
						<br/>
						<br/>
						<iframe width="560" height="315" src="https://www.youtube.com/embed/nkhpGC10OVw"  allow="autoplay; encrypted-media" allowfullscreen></iframe>
					</div>
				</div>
			</div>
		</div>
		
		<div class="larghezza-cento">
			<div class="col-lg-12 larghezza-cento team">
               		
				<h1>OUR TEAM</h1>
				
			</div>
		</div>
		
		<div class="larghezza-ottanta margine-sx">	
			<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 schede">
					<br/>
				  <div class="card h-100 text-center">
					<br/>
					<img class="card-img-top" src="images/card1.jpg" alt="">
					<br/>
					<br/>
					<div class="card-body">
					  <h4 class="card-title">Taj Burrow</h4>
					  <h6 class="card-subtitle mb-2 text-muted">@tajamos</h6>
					  <p class="card-text"><img src="images/ico-location.svg" alt="" /> Yallingup, Australia</p>
					  <br/>
					</div>
				  </div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 schede">
					
					<br/>
					<br/>
				  <div class="card h-100 text-center">
					<br/>
					<img class="card-img-top" src="images/card2.jpg" alt="">
					<br/>
					<br/>
					<div class="card-body">
					  <h4 class="card-title">Malia Manuel</h4>
					  <h6 class="card-subtitle mb-2 text-muted">@maliamanuel</h6>
					  <p class="card-text"><img src="images/ico-location.svg" alt="" /> Wailua, Hi</p>
						 <br/>
					</div>
				  </div>
					
				
			</div>
			<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 schede">
					<br/>
				  <div class="card h-100 text-center">
					<br/>
					<img class="card-img-top" src="images/card3.jpg" alt="">
					<br/>
					<br/>
					<div class="card-body">
					  <h4 class="card-title">Ian Walsh</h4>
					  <h6 class="card-subtitle mb-2 text-muted">@ian.walsh</h6>
					  <p class="card-text"><img src="images/ico-location.svg" alt="" /> Maui, Hi</p>
						 <br/>
					</div>
				  </div>
					
				
			</div>
			<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 schede">
					<br/>
					<br/>
				  <div class="card h-100 text-center">
					<br/>
					<img class="card-img-top" src="images/card4.jpg" alt="">
					<br/>
					<br/>
					<div class="card-body">
					  <h4 class="card-title">Macy Callaghan</h4>
					  <h6 class="card-subtitle mb-2 text-muted">@macyjanecallaghan</h6>
					  <p class="card-text"><img src="images/ico-location.svg" alt="" /> San Clemente, CA</p>
						 <br/>
					</div>
				  </div>
					
				
			</div>
		</div>


		<div class="col-lg-12 larghezza-cento">
			
				
			<br/>
			<br/>
			<h5>LATEST UPDATE</h5>
			<br/>
			<br/>	
		</div>


		<div class="larghezza-ottanta">	
			<div class="col-xs-0 col-sm-0 col-md-0 col-lg-0"></div>
			
			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 latest">
				<div class="col-xs-6 col-sm-12 col-md-12 col-lg-6">

					<img src="images/latest1.jpg" class="img-responsive" alt="" />
					<br/>
				</div>	
					
				<div class="col-xs-6 col-sm-12 col-md-12 col-lg-6">
	
					<p>Ellie Turner and Jobe Harris have taken out the 2016 British National Surf Championship</p>
					
				</div>
			</div>
			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 latest">
				<div class="col-xs-6 col-sm-12 col-md-12 col-lg-6">

					<img src="images/latest2.jpg" class="img-responsive" alt="" />
					<br/>
				</div>	
					
				<div class="col-xs-6 col-sm-12 col-md-12 col-lg-6">
	
					<p>A large gruop of surfers invaded the coast of La Jolla Shores, in California, with a single goal in mind</p>
					
				</div>
			</div>
			<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 latest">
				<div class="col-xs-6 col-sm-12 col-md-12 col-lg-6">

					<img src="images/latest3.jpg" class="img-responsive" alt="" />
					<br/>
				</div>	
					
				<div class="col-xs-6 col-sm-12 col-md-12 col-lg-6">
	
					<p>Surfboards are constantly evolving and there are multiple board designs for a broad range of environments</p>
					
				</div>
			</div>

		</div>
		
		<div class="col-lg-12 larghezza-cento team">
			
			<button type="button" class="btn btn-primary">view all posts</button>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
		</div>
		
		<div class="larghezza-ottanta">
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
					
						<img src="images/instagram1.jpg" class="img-responsive center-block" alt="" /> 
						
					
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
					
						<img src="images/instagram2.jpg" class="img-responsive center-block" alt="" /> 			
				</div>
				
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
					
						<img src="images/instagram3.jpg" class="img-responsive center-block" alt="" /> 
				</div>
				
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
					
						<img src="images/instagram4.jpg" class="img-responsive center-block" alt="" /> 

				</div>
						
			</div>
			<div class="col-xs-0 col-sm-6 col-md-6 col-lg-6">
				<br/>
				<br/>
			</div>	
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
				<br/>
				<img src="images/facebook.jpg" class="img-responsive center-block" alt="" /> 
				<br/>
			</div>	
		</div>
	</main>
	
	<?php include("inc/inc_footer.php"); ?>
</body>
	
</html>

